### ISSUE TITLE
Draft alignment

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#10]
The bilingual ab-ru files in the draft could be aligned with a current translation model. There are some unmainted tools to align documents, so we can also customize [NLTK align](http://www.nltk.org/_modules/nltk/align/bleu.html) from scratch.

**Comment by danielinux7** [comment]
This [BLEU alignment ](https://github.com/rsennrich/Bleualign) tool can be used right out of the box. 
I think BLEU alignment would require a good translation model.

**Comment by Bachstelze** [comment]
Bleu alignment seems worth a try. Though it is limited to complete sentences or longer sequences due to do the n-gram comparisons. On short phrases we will only get matches, if the translation is nearly identical - in which case we don't really need it as additional training data.

**Comment by danielinux7** [comment]
This is in your domain, you have more knowledge in this, if you think NLTK align can be helpful, then why not!
Meanwhile I am training the transformer, I keep testing it's BLEU score every 10k steps, it is still climbing up.

**Comment by Bachstelze** [comment]
Bleualign covers the basic NLTK align functions. So we can us multiple references as comparison and align also shorter sentences.
