### ISSUE TITLE
Ab-Ru corpus correction

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#11]
A NMT model is quite sensitive to incorrect training data. The current filtration yields many cases which can be corrected in the original files. In such way we minimize the side effects of wrong alignments or sentence tokenization and we can utilize more data with less filtration.

Possible correction steps are:
- Analyze the verbose output of the joining script.
- Get the difference lines of the bifixed corpus.
- Score the parallel sentences with a current translation model.

**Comment by Bachstelze** [comment]
The filtration of corrected sentences in the splitting script is now corrected due to https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/373072b99760143253ebf066d881e392df138d48 Some parallel sentences like the abkhazian "Иашарыла умҩа қәҵоуп." and the russian "Кто ещё такой, как ты?" don't share the same punctuation marks. Perhaps we should filter them out?

**Comment by danielinux7** [comment]
In this case, it has the wrong meaning but let's assume another example.
If the punctuation is wrong, but the translation is right. would that still be valid data?

**Comment by Bachstelze** [comment]
Sometimes the punctuations isn't completely different and valid like "!" and "!?", but differ punctuations are a good indicator for a wrong translation.

**Comment by danielinux7** [comment]
> Score the parallel sentences with a current translation model.

How would you do that? just translate sentences and compare them to get the score with [Bleualign](https://github.com/rsennrich/Bleualign)? There seems to be other ways, i.e a trained sentence embedding model [LASER](https://github.com/facebookresearch/LASER)
I think this issue should be split into 3 subtasks for each step.

**Comment by danielinux7** [comment]
Kalle, could you create a task for each of the three steps, and describe each task?

**Comment by Bachstelze** [comment]
I think that we don't have the resources for a laser project. A good translation model can generate multiple suggestions in both ways. It seems like the current model isn't good enough for it.

**Comment by Bachstelze** [comment]
The join corpus script has now a hard punctuation filter which is inspired by [Aligning parallel bilingual corpora statistically with punctuation criteria](https://www.researchgate.net/publication/228809191_Aligning_parallel_bilingual_corpora_statistically_with_punctuation_criteria). There are around 10k translation pairs that don't have the exact same punctuations.

**Comment by danielinux7** [comment]
> The join corpus script has now a hard punctuation filter which is inspired by Aligning parallel bilingual corpora statistically with punctuation criteria. There are around 10k translation pairs that don't have the exact same punctuations.

Should we assign this task to you? or maybe you could create an issue that describes what you did then close it.
All this should be within the multilingual project sprint, that way it's easier to track tasks/issues down, you can also create a task/ user story/ bug in the backlog for the next sprint planning. 
Getting organized can help us in many ways as you know, we could Skype for the next sprint planning on Monday?
https://github.com/danielinux7/Multilingual-Parallel-Corpus/projects/3?fullscreen=true
