### ISSUE TITLE
Testing the integrity of the ab-ru Transformer model

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#12]
I keep updating the model in Kaggle, the data that I am using and the latest model, here are the links:
https://www.kaggle.com/nartaa/ab-ru-transformer
https://www.kaggle.com/nartaa/abrutransformer
https://www.kaggle.com/nartaa/abrudata

This needs testing and QA, could you double check my work?
Here is the python code I am using to detokenize:
```
import io
import re
from mosestokenizer import *
out_pre = ""
pre_list = []
in_pre = io.open("/content/tgt-test.txt",'r', encoding="utf-8")
pre_list.extend(in_pre.readlines())
for i, item in enumerate(pre_list):
  pre_list[i] = re.sub(r" ","",pre_list[i])
  pre_list[i] = re.sub(r"▁"," ",pre_list[i])
detokenize = MosesDetokenizer('ru')
for i, item in enumerate(pre_list):
  temp = item.strip().split(" ")
  item = detokenize(temp)
  out_pre = out_pre + item.lower() + "\n"
f_pre = open("/content/tgt-test-dec.txt","w")
f_pre.writelines(out_pre)
f_pre.close()
```

**Comment by Bachstelze** [comment]
I mostly use sed with the terminal to detokenize like `sed -i "s/@@ //g"  pred.txt`
It will take some time the setup, configure and test a tensorflow environment for me.

**Comment by danielinux7** [comment]
Here is a colab notebook, everything is set there:
https://colab.research.google.com/drive/1gvSvV4t82MgZ5C7Gr-A-vtsAiK6N1S_i
If you come across an issue, Please let me know.
The test and validation data should have no duplicates, but could you double check, maybe I missed something!

**Comment by Bachstelze** [comment]
The results are looking promising so far. We could use a new aligned draft corpus for a proper validation.

**Comment by Bachstelze** [comment]
The alignment of a validation corpus is conducted in #10 .

**Comment by Bachstelze** [comment]
There will be further testing with a new corpus in #24
