### ISSUE TITLE
Replace the latin letters to it's cyrillic equivalent  !important

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#13]
I came across a serious issue in the dictionary, the rest of the corpus should be checked also.
In the abkhazian dictionary text, the latin letter a (U+0041, U+0061) is used instead of the Cyrillic letter a (U+0410, U+0430)
All the letters that look like latin letters should be checked and replaced if needed to it's Cyrillic equivalent!

**Comment by danielinux7** [comment]
It seems the issue is coming from parsing the dictionary, when replacing stressed letters, they should be replaced with the Cyrillic equivalent. not the Latin that looks like it but has a different Unicode.
Example:
абажу́р --> абажур and not абажyр, the first у is  Cyrillic Small Letter U U+0443, the second y is Latin Small Letter Y U+0079

**Comment by Bachstelze** [comment]
There was the same problem with 'е'.

**Comment by danielinux7** [comment]
Yes, 'a,e and y'

**Comment by Bachstelze** [comment]
I think that also "э" had wrong accents. Which should be fixed in the current version that has no only the defined cyrillic letters.

**Comment by danielinux7** [comment]
> I think that also "э" had wrong accents. Which should be fixed in the current version that has no only the defined cyrillic letters.

Can you give an example?

**Comment by Bachstelze** [comment]
There have been also accents which are converted from 'э́' to 'э'. Moreover, words with punctuations are now filtered. I am going to close this issue because there are no more Latin letters in the dictionary.

**Comment by danielinux7** [comment]
> There have been also accents which are converted from 'э́' to 'э'.
э in both have the same unicode "\u044d", I'm not sure why you think it was an issue.

**Comment by Bachstelze** [comment]
'э́' is not in the alphabet. If it is not converted, then the translation gets filtered out.
