### ISSUE TITLE
Add capability to join_corpus tool

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#14]
The following enhancements:
- [ ] pass the dictionaries, synonym dictionaries and the parallel corpus as a command line argument.
- [ ] ability to generate paraphrases without splitting data to train, test and validation sets.
- [ ] ability to import join_corpus to a python script and use it's functionality.

**Comment by Bachstelze** [comment]
A hint in addition to 2- for the current use: There is the script "utils/parallel_paraphrasing.py" which can generate the plain paraphrases.

**Comment by Bachstelze** [comment]
The option to pass the corpus file and only generate paraphrases was added with https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/4b1339a394ad2d143e45fd7f77634f49a53b09ca
To call the join corpus script as subprocess, you can use: `subprocess.call("python3 join_corpus.py --dictionary --paraphrase 1 0.7 2.25 10 50 1 0 0 ru-ab-parallel-27-07.bifixed", shell=True)`
We should add the capability to pass the (synonym) dictionaries with #25, for now we are limited to the specific abkhazian and russian dictionaries.

**Comment by Bachstelze** [comment]
The point "ability to import join_corpus to a python script and use it's functionality." should be solved over a main function and a pip package.

**Comment by Bachstelze** [comment]
The creation of a [proper pip package](https://jwodder.github.io/kbits/posts/pypkg-mistakes/) can last one sprint. I am going to put this issue to the backlog, since we both know how to cooperate with the command line.
