### ISSUE TITLE
MASS training

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#20]
Pretraining a whole transformer encoder and decoder with MASS.

**Comment by Bachstelze** [comment]
The hardware isn't surly available in this week. It is questionable whether we need this pretraining, if we directly leverage the monolingual corpus through back-translation into the training #31.

**Comment by Bachstelze** [comment]
I think we can close this issue and work with simple transformers or use the pretraining of [mBART](https://huggingface.co/transformers/model_doc/mbart.html). Do we have a good abkhaz sentencepiece model which we could add to the multilingual model?

**Comment by danielinux7** [comment]
I think what's key is to provide the data, choosing the architecture becomes optional, currently I am training on TransformerRelative.
https://www.kaggle.com/nartaa/abkhazianrussian-parallel-corpus
We have different sentencepiece models:
v1 vocab size:28500, maximum piece length: 14, BLEU = 31.00
v2 vocab size:25000, maximum piece length: 12, BLEU = 30.93
v3 vocab size:22000, maximum piece length: 10, BLEU = 30.39
v4 vocab size:19000, maximum piece length: 8, BLEU = 30.08
v5 vocab size:16000, maximum piece length: 6, BLEU = 28.16
