### ISSUE TITLE
Validation and testing corpus

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#24]
We need a corpus around 5000 lines each for a proper validation and testing. The corpus should be new aligned.
Following https://github.com/danielinux7/Multilingual-Parallel-Corpus/issues/12

**Comment by danielinux7** [comment]
Around 4.5k testing corpus https://github.com/danielinux7/Multilingual-Parallel-Corpus/issues/59 is done.
