### ISSUE TITLE
R&D

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#27]
- [ ] Studying the Abkhazian language.
- [ ] Studying Tensorflow.

**Comment by Bachstelze** [comment]
I am also interested.
Do you know a curriculum about the Abkhazian language in German or which is translatable into it?
FYI there is a good [explanation of the transformer in pytorch](http://nlp.seas.harvard.edu/2018/04/03/attention.html). The transformer seems to be a universal standard for many tasks and further developments e.g. the xtransformer, BERT, BART or GPT.

**Comment by danielinux7** [comment]
The best curriculum to learn a language in my opinion is to speak it in practice, in order to do that you should come to Abkhazia then I can guarantee that you will start speaking it in 6 months.
Beside this, I'll look up some books to get your feets wet.
Thanks for the transformer link.

**Comment by Bachstelze** [comment]
There is an [introduction to study the Caucasian languages in German](https://glottolog.org/resource/reference/id/18941) which is [available in my library](https://wlb.ibs-bw.de/aDISWeb/app?service=direct/0/Home/$DirectLink&sp=SOPAC00&sp=SAKSWB-IdNr1080353879). I am going to read it, before i will question Paul. Moreover, [glottolog](https://glottolog.org/resource/languoid/id/abkh1244) lists many publication with some about the [abkhazian grammar](https://abkhazology.files.wordpress.com/2010/05/13634835-georgianabkhaziangrammar.pdf), but i think it is written in Georgian.
