### ISSUE TITLE
Corpus generation with back-translation

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#31]
The current generation script can't mix in back-translation data. This data could also be filtered like the human translations, but it shouldn't be used for the paraphrase generation. Furthermore, a labeling and scaling factor would be handy.
This development puncture includes:
- [x] generate back-translation of the abkhazian, monolingual corpus
- [ ] implement the features in the join corpus script
- [ ] test the corpus with a trained model

**Comment by danielinux7** [comment]
generate back-translation of the abkhazian, monolingual corpus
This task is done.
https://www.kaggle.com/nartaa/abkhazianrussian-parallel-corpus
https://www.kaggle.com/nartaa/abrudata

    a labeling and scaling factor would be handy.
Labeling (<ru> <bt> <v6>) and scaling (5 models based on different BPE splitting) are being used.

     implement the features in the join corpus script
@Bachstelze Are you still planning on implementing this part?

     test the corpus with a trained model
What do you mean by that? could you elaborate on this point?

**Comment by Bachstelze** [comment]
> Labeling (<ru> <bt> <v6>) and scaling (5 models based on different BPE splitting) are being used.

This is very useful to train good translation models. The corpus test is successful, if you get better results than without the backtranslation data. What is your experience?

> @Bachstelze Are you still planning on implementing this part?

Since we don't actually use it, i think we don't need this feature in the join corpus script.

**Comment by danielinux7** [comment]
@Bachstelze 
    The corpus test is successful, if you get better results than without the back-translation data. What is your experience?
If I understand you correctly, I have trained a model with augmented back-translation data, for the first iteration, the BLEU score for the test corpus increased by ~4.5 BLEU than the model without back-translation.
