### ISSUE TITLE
Rare word counting for paraphrases

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#32]
It is beneficial to fill in seldom words in the corpus, if we want to use just a small amount of paraphrases.

**Comment by danielinux7** [comment]
Because you added this task to the current sprint, I took the liberty to move it to the Todo column.

**Comment by Bachstelze** [comment]
The feature and the corresponding input option and flag are committed.
Further improvements are implemented in #38 #39.
