### ISSUE TITLE
FileNotFoundError Join_corpus script

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#33]
When using my own corpus.txt file with the command line example, I get the following error:
```
cd Multilingual-Parallel-Corpus/tools
python3 join_corpus.py --dictionary --paraphrase 1 0.7 2.25 10 50 1 0 0 /content/corpus.txt
```
```
[Errno 2] No such file or directory: 'Multilingual-Parallel-Corpus/tools'
/content/Multilingual-Parallel-Corpus/tools
Traceback (most recent call last):
  File "join_corpus.py", line 302, in <module>
    ab_text_train = io.open(folder+current_date+'_corpus_abkhaz.train',"w+", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'joined_translation_data/08-25-2020_corpus_abkhaz.train'
```

**Comment by Bachstelze** [comment]
The directory `tools/joined_translation_data` is missing. Quick fix: create it by hand.

**Comment by Bachstelze** [comment]
Fixed with https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/a8bb29c84816ca407bf2b30fa3e5f282036256a7
The dicrectory is created if it doesn't exists.

**Comment by Bachstelze** [comment]
It shouldn't block #35 anymore.

**Comment by Bachstelze** [comment]
If the content directory is on the same level as the tools directory then the path should be `../content/corpus.txt`

**Comment by danielinux7** [comment]
On Colab, it still worked with just /content/corpus.txt
