### ISSUE TITLE
--punctuation usage with join_corpus script

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#34]
How can I use this option to filter out a parallel corpus file of unwanted sentences, could you give an example?
```
  --punctuation      We use the punctuation criteria as filter in such way
                     that each translation have the same order of sentence
                     signs. The sentence signs are ".:!?0-9…()[]«»".
```

**Comment by Bachstelze** [comment]
It is an optional parameter  like an on-off switch which can be used by adding "--punctuation" to the command string.

**Comment by danielinux7** [comment]
How can I use it to filter out the parallel corpus without generating paraphrases?

**Comment by Bachstelze** [comment]
Yes, but the maximum length ratio seems to be high. 0.7 is 7/10, the reverse fraction is 10/7 or about 1.42. Perhaps we should unify them?

**Comment by Bachstelze** [comment]
Those details shouldn't block #35.
