### ISSUE TITLE
Python script to identify mismatched punctuation

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#57]
Problem Description
For Neural machine translation, it is important to have identical punctuation marks on both source and target text.

Solution
A python script where i can pass a tsv file, once I run the python script, I should get back as a result two tsv files, one that has the text with identical punctuation, a second file contains the text with mismatched punctuation.

Resources
This code could be helpful to look at: https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/65667b16cb4ac5c96c922cfb0b00e14f06d947d9
You can try one of the tsv files in the ab-ru folder.
Once the script is ready, it should be pushed to the utils folder in this repository.

**Comment by danielinux7** [comment]
@Plkmoi Hello Nara,
Are you still working on this issue?

**Comment by Plkmoi** [comment]
Can you share an example of what you are asking?

**Comment by danielinux7** [comment]
@Plkmoi 
I merged and made some changes, you can have a look at the code. https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/fef1e633ac5e385897f58a1589190edc9a0ac6d1
