### ISSUE TITLE
Parse Ru-Ab dictionary

### ISSUE THREAD

**Issue by danielinux7** [danielinux7/Multilingual-Parallel-Corpus#61]
**Ахҳәаа**
1. I got a hold of the Russian Abkhazian dictionary in docx format, as well as a csv file (an export of an sql file). 
2. I got a hold of StarDic from the Abkhazian NowLinux.

**Ауадаҩрақәа/Аӡбара**

1. I think it's better if we parse the docx ourselves, the cvs seems to have many errors.
2. Export StarDic from Abkhazian NowLinux, then add it to the current ab-ru dictionary tsv file. 

**Азхьарԥшқәа:**

1. https://en.wikipedia.org/wiki/StarDict
2. https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/dictionary.tsv
3. https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/ru-ab-dic.zip
4. https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/ab-ru-dic.csv

**Comment by danielinux7** [comment]
@Bachstelze Would you be interested to handle this one?

**Comment by Bachstelze** [comment]
No, i don't understand the issue and the errors. We have already a processed dictionary with
https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/dictionary.ab
https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/dictionary.ru
https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/dictionary_prescript.ab
https://github.com/danielinux7/Multilingual-Parallel-Corpus/blob/master/ab-ru/draft/dictionary_prescript.ru
which are combined into a tsv: https://raw.githubusercontent.com/Bachstelze/Multilingual-Parallel-Corpus/master/ab-ru/dictionary.tsv from https://github.com/danielinux7/Multilingual-Parallel-Corpus/issues/2

**Comment by danielinux7** [comment]
Ok, I'll assign the issue for myself.
I recently restricted commits, because more people might be involved, to keep track and review changes.

Could you open a pull request and add the tsv dictionary file?

On a side note, It would be nice to have you back actively on this project, maybe we could arrange a retrospective meeting.
