### ISSUE TITLE
Multilingual dictionary parsing

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#9]
It would be a good start for other low-resource languages to parse translation dictionaries.
If there are only dictionary images, then we should start with the support of [OCR](https://github.com/JaidedAI/EasyOCR).
Which translation dictionaries could be used?
- [ ] Adyghe OCR #16

**Comment by danielinux7** [comment]
The languages that are from the same family,: east and west Adyghe languages, Abaza language and Ubykh language.
I'll do some research.

**Comment by danielinux7** [comment]
I think in agile terms, this is more like a story, it is a continuous effort, so maybe it should be moved to the back log, coined as a user story, and create tasks that is related to it, I added 3 dictionaries that needs OCR in the draft folder, also resources in the readme file.

**Comment by Bachstelze** [comment]
The development of OCR tools is a complete own project, so we should translate the parsed ab-ru dictionary with glosbe. The
